"use client";

import { Edit3, Plus, Trash2 } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";

import { useAuth } from "@/components/auth-provider";
import { DashboardShell } from "@/components/dashboard-shell";
import { Modal } from "@/components/modal";
import { ProtectedRoute } from "@/components/protected-route";
import { EmptyState, ErrorMessage, LoadingState } from "@/components/states";
import { api } from "@/lib/api";
import { formatCurrency, formatDate } from "@/lib/format";
import type { Category, Order, OrderStatus, Review, Service, User, UserRole } from "@/types";

type Tab="users"|"categories"|"services"|"orders"|"reviews";

function AdminContent(){
  const {token}=useAuth(); const [tab,setTab]=useState<Tab>("users"); const [users,setUsers]=useState<User[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [services,setServices]=useState<Service[]>([]); const [orders,setOrders]=useState<Order[]>([]); const [reviews,setReviews]=useState<Review[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [categoryModal,setCategoryModal]=useState(false); const [editingCategory,setEditingCategory]=useState<Category|null>(null); const [categoryName,setCategoryName]=useState(""); const [categoryDescription,setCategoryDescription]=useState("");
  const load=useCallback(async()=>{if(!token)return;try{const [u,c,s,o,r]=await Promise.all([api.get<User[]>("/api/users",token),api.get<Category[]>("/api/categories"),api.get<Service[]>("/api/services?limit=100"),api.get<Order[]>("/api/orders",token),api.get<Review[]>("/api/reviews")]);setUsers(u.data);setCategories(c.data);setServices(s.data);setOrders(o.data);setReviews(r.data);}catch(reason){setError(reason instanceof Error?reason.message:"Could not load admin workspace");}finally{setLoading(false);}},[token]); useEffect(()=>{void load();},[load]);
  function openCategory(category?:Category){setEditingCategory(category||null);setCategoryName(category?.name||"");setCategoryDescription(category?.description||"");setCategoryModal(true);}
  async function saveCategory(event:FormEvent){event.preventDefault();if(!token)return;try{const body={name:categoryName,description:categoryDescription||undefined};if(editingCategory)await api.patch(`/api/categories/${editingCategory.id}`,body,token);else await api.post("/api/categories",body,token);setCategoryModal(false);setMessage(editingCategory?"Category updated.":"Category created.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not save category");}}
  async function remove(path:string,label:string){if(!token||!window.confirm(`Soft-delete this ${label}?`))return;try{await api.delete(path,token);setMessage(`${label[0].toUpperCase()+label.slice(1)} deleted.`);await load();}catch(reason){setError(reason instanceof Error?reason.message:`Could not delete ${label}`);}}
  async function updateUserRole(user:User,role:UserRole){if(!token)return;try{await api.patch(`/api/users/${user.id}`,{role},token);setMessage("User role updated.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not update user");}}
  async function updateOrder(order:Order,status:OrderStatus){if(!token||status===order.status)return;try{await api.patch(`/api/orders/${order.id}`,{status},token);setMessage("Order status updated.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not update order");}}
  const tabs:Tab[]=["users","categories","services","orders","reviews"];
  return <DashboardShell eyebrow="Administration" title="Marketplace operations" description="Manage access, taxonomy, offers, delivery, and client feedback from one workspace." actions={tab==="categories"?<button className="button button-brand" onClick={()=>openCategory()}><Plus className="size-4"/>Add category</button>:undefined}><div className="stat-grid"><div className="stat"><span>Users</span><strong>{users.length}</strong></div><div className="stat"><span>Categories</span><strong>{categories.length}</strong></div><div className="stat"><span>Services</span><strong>{services.length}</strong></div><div className="stat"><span>Open orders</span><strong>{orders.filter(o=>!['COMPLETED','CANCELLED'].includes(o.status)).length}</strong></div></div><div className="dashboard-tabs">{tabs.map(item=><button key={item} className={`dashboard-tab ${tab===item?"active":""}`} onClick={()=>setTab(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div>{message&&<div className="success-message mb-4">{message}</div>}{error&&<div className="mb-4"><ErrorMessage message={error}/></div>}{loading?<LoadingState label="Loading administration"/>:<AdminTable tab={tab} users={users} categories={categories} services={services} orders={orders} reviews={reviews} onCategoryEdit={openCategory} onDelete={remove} onRole={updateUserRole} onOrder={updateOrder}/>}<Modal title={editingCategory?"Edit category":"Create category"} open={categoryModal} onClose={()=>setCategoryModal(false)}><form className="form-grid" onSubmit={saveCategory}><div className="field"><label htmlFor="categoryName">Name</label><input id="categoryName" className="input" minLength={2} maxLength={100} value={categoryName} onChange={e=>setCategoryName(e.target.value)} required/></div><div className="field"><label htmlFor="categoryDescription">Description</label><textarea id="categoryDescription" className="textarea" maxLength={500} value={categoryDescription} onChange={e=>setCategoryDescription(e.target.value)}/></div><button className="button button-brand">{editingCategory?"Save changes":"Create category"}</button></form></Modal></DashboardShell>;
}

function AdminTable({tab,users,categories,services,orders,reviews,onCategoryEdit,onDelete,onRole,onOrder}:{tab:Tab;users:User[];categories:Category[];services:Service[];orders:Order[];reviews:Review[];onCategoryEdit:(category:Category)=>void;onDelete:(path:string,label:string)=>void;onRole:(user:User,role:UserRole)=>void;onOrder:(order:Order,status:OrderStatus)=>void}){
  if(tab==="users")return users.length===0?<EmptyState title="No users" message="Registered users will appear here."/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Joined</th><th>Action</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td className="font-semibold">{user.name}</td><td>{user.email}</td><td><select className="select !min-h-9" value={user.role} onChange={e=>onRole(user,e.target.value as UserRole)}><option>CLIENT</option><option>FREELANCER</option><option>ADMIN</option></select></td><td>{user.createdAt?formatDate(user.createdAt):"-"}</td><td><button className="icon-button" onClick={()=>onDelete(`/api/users/${user.id}`,"user")} title="Delete user"><Trash2 className="size-4"/></button></td></tr>)}</tbody></table></div>;
  if(tab==="categories")return categories.length===0?<EmptyState title="No categories" message="Add a category to organize services."/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Description</th><th>Actions</th></tr></thead><tbody>{categories.map(category=><tr key={category.id}><td className="font-semibold">{category.name}</td><td className="max-w-[500px] text-[var(--muted)]">{category.description||"No description"}</td><td><div className="table-actions"><button className="icon-button" onClick={()=>onCategoryEdit(category)} title="Edit category"><Edit3 className="size-4"/></button><button className="icon-button" onClick={()=>onDelete(`/api/categories/${category.id}`,"category")} title="Delete category"><Trash2 className="size-4"/></button></div></td></tr>)}</tbody></table></div>;
  if(tab==="services")return services.length===0?<EmptyState title="No services" message="Published services will appear here."/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Service</th><th>Freelancer</th><th>Category</th><th>Price</th><th>Status</th><th>Action</th></tr></thead><tbody>{services.map(service=><tr key={service.id}><td className="max-w-[270px] font-semibold">{service.title}</td><td>{service.freelancer.name}</td><td>{service.category.name}</td><td>{formatCurrency(service.price)}</td><td><span className="badge">{service.status}</span></td><td><button className="icon-button" onClick={()=>onDelete(`/api/services/${service.id}`,"service")} title="Delete service"><Trash2 className="size-4"/></button></td></tr>)}</tbody></table></div>;
  if(tab==="orders")return orders.length===0?<EmptyState title="No orders" message="Marketplace orders will appear here."/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Service</th><th>Client</th><th>Freelancer</th><th>Price</th><th>Status</th><th>Created</th></tr></thead><tbody>{orders.map(order=><tr key={order.id}><td className="max-w-[230px] font-semibold">{order.service.title}</td><td>{order.client.name}</td><td>{order.service.freelancer.name}</td><td>{formatCurrency(order.price)}</td><td><select className="select !min-h-9" value={order.status} onChange={e=>onOrder(order,e.target.value as OrderStatus)}>{["PENDING","IN_PROGRESS","COMPLETED","CANCELLED"].map(status=><option key={status}>{status}</option>)}</select></td><td>{formatDate(order.createdAt)}</td></tr>)}</tbody></table></div>;
  return reviews.length===0?<EmptyState title="No reviews" message="Client reviews will appear here."/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Service</th><th>Client</th><th>Rating</th><th>Comment</th><th>Date</th><th>Action</th></tr></thead><tbody>{reviews.map(review=><tr key={review.id}><td className="max-w-[220px] font-semibold">{review.service.title}</td><td>{review.client.name}</td><td>{review.rating}/5</td><td className="max-w-[300px] text-[var(--muted)]">{review.comment||"No comment"}</td><td>{formatDate(review.createdAt)}</td><td><button className="icon-button" onClick={()=>onDelete(`/api/reviews/${review.id}`,"review")} title="Delete review"><Trash2 className="size-4"/></button></td></tr>)}</tbody></table></div>;
}
export default function AdminDashboard(){return <ProtectedRoute role="ADMIN"><AdminContent/></ProtectedRoute>;}
