"use client";

import { MessageSquarePlus, XCircle } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";

import { useAuth } from "@/components/auth-provider";
import { DashboardShell } from "@/components/dashboard-shell";
import { Modal } from "@/components/modal";
import { ProtectedRoute } from "@/components/protected-route";
import { EmptyState, ErrorMessage, LoadingState } from "@/components/states";
import { api } from "@/lib/api";
import { formatCurrency, formatDate } from "@/lib/format";
import type { Order, Review } from "@/types";

function ClientDashboardContent(){
  const {user,token}=useAuth(); const [orders,setOrders]=useState<Order[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [reviewOrder,setReviewOrder]=useState<Order|null>(null); const [rating,setRating]=useState(5); const [comment,setComment]=useState(""); const [submitting,setSubmitting]=useState(false);
  const load=useCallback(async()=>{if(!token)return;try{const result=await api.get<Order[]>("/api/orders",token);setOrders(result.data);}catch(reason){setError(reason instanceof Error?reason.message:"Could not load orders");}finally{setLoading(false);}},[token]); useEffect(()=>{void load();},[load]);
  async function cancel(order:Order){if(!token||!window.confirm("Cancel this pending order?"))return;setError("");try{await api.patch(`/api/orders/${order.id}`,{status:"CANCELLED"},token);setMessage("Order cancelled.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not cancel order");}}
  async function submitReview(event:FormEvent){event.preventDefault();if(!token||!reviewOrder)return;setSubmitting(true);setError("");try{await api.post<{review:Review}>("/api/reviews",{serviceId:reviewOrder.serviceId,rating,comment:comment.trim()||undefined},token);setMessage("Review published.");setReviewOrder(null);setComment("");setRating(5);}catch(reason){setError(reason instanceof Error?reason.message:"Could not publish review");}finally{setSubmitting(false);}}
  const completed=orders.filter((order)=>order.status==="COMPLETED").length;
  return <DashboardShell eyebrow="Client workspace" title={`Welcome, ${user?.name.split(" ")[0]}`} description="Track every order from brief to delivery, and review completed work."><div className="stat-grid"><div className="stat"><span>Total orders</span><strong>{orders.length}</strong></div><div className="stat"><span>In progress</span><strong>{orders.filter(o=>o.status==="IN_PROGRESS").length}</strong></div><div className="stat"><span>Completed</span><strong>{completed}</strong></div><div className="stat"><span>Account</span><strong className="!text-base">{user?.email}</strong></div></div>{message&&<div className="success-message mb-4">{message}</div>}{error&&<div className="mb-4"><ErrorMessage message={error}/></div>}{loading?<LoadingState label="Loading your orders"/>:orders.length===0?<EmptyState title="No orders yet" message="Browse services and place your first project order."/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Service</th><th>Freelancer</th><th>Placed</th><th>Price</th><th>Status</th><th>Action</th></tr></thead><tbody>{orders.map((order)=><tr key={order.id}><td className="max-w-[260px] font-semibold">{order.service.title}</td><td>{order.service.freelancer.name}</td><td>{formatDate(order.createdAt)}</td><td>{formatCurrency(order.price)}</td><td><span className={`badge ${order.status==="COMPLETED"?"badge-green":order.status==="CANCELLED"?"badge-red":"badge-yellow"}`}>{order.status.replace("_"," ")}</span></td><td><div className="table-actions">{order.status==="PENDING"&&<button className="icon-button" onClick={()=>cancel(order)} title="Cancel order"><XCircle className="size-4"/></button>}{order.status==="COMPLETED"&&<button className="button button-outline" onClick={()=>setReviewOrder(order)}><MessageSquarePlus className="size-4"/>Review</button>}</div></td></tr>)}</tbody></table></div>}<Modal title="Review completed work" open={Boolean(reviewOrder)} onClose={()=>setReviewOrder(null)}><form className="form-grid" onSubmit={submitReview}><div className="field"><label htmlFor="rating">Rating</label><select id="rating" className="select" value={rating} onChange={(e)=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(value=><option key={value} value={value}>{value} star{value===1?"":"s"}</option>)}</select></div><div className="field"><label htmlFor="comment">Comment</label><textarea id="comment" className="textarea" value={comment} onChange={(e)=>setComment(e.target.value)} maxLength={1000} placeholder="What went well?"/></div><button className="button button-brand" disabled={submitting}>{submitting?"Publishing...":"Publish review"}</button></form></Modal></DashboardShell>;
}
export default function ClientDashboard(){return <ProtectedRoute role="CLIENT"><ClientDashboardContent/></ProtectedRoute>;}
