"use client";

import { ChevronLeft, ChevronRight, Search } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { FormEvent, Suspense, useCallback, useEffect, useState } from "react";
import { ServiceCard } from "@/components/service-card";
import { EmptyState, ErrorMessage, LoadingState } from "@/components/states";
import { api } from "@/lib/api";
import type { Category, PaginationMeta, Service, ServiceStatus } from "@/types";

function ServicesContent() {
  const params=useSearchParams(); const [search,setSearch]=useState(params.get("search")??""); const [categoryId,setCategoryId]=useState(params.get("categoryId")??""); const [status,setStatus]=useState<ServiceStatus|"">((params.get("status") as ServiceStatus)??"ACTIVE"); const [page,setPage]=useState(1); const [categories,setCategories]=useState<Category[]>([]); const [services,setServices]=useState<Service[]>([]); const [meta,setMeta]=useState<PaginationMeta>({page:1,limit:9,total:0,totalPages:0}); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{const query=new URLSearchParams({page:String(page),limit:"9"});if(search.trim())query.set("search",search.trim());if(categoryId)query.set("categoryId",categoryId);if(status)query.set("status",status);try{const result=await api.get<Service[]>(`/api/services?${query}`);setServices(result.data);if(result.meta)setMeta(result.meta);}catch(reason){setError(reason instanceof Error?reason.message:"Could not load services");}finally{setLoading(false);}},[categoryId,page,search,status]);
  useEffect(()=>{api.get<Category[]>("/api/categories").then((result)=>setCategories(result.data)).catch(()=>undefined);},[]); useEffect(()=>{void load();},[load]);
  function submit(event:FormEvent){event.preventDefault();setPage(1);void load();}
  return <><section className="page-header"><div className="shell"><p className="eyebrow">Service marketplace</p><h1>Find the right specialist.</h1><p>Search live offers, narrow by discipline, and compare delivery terms before you order.</p></div></section><main className="section"><div className="shell"><form className="filters" onSubmit={submit}><div className="relative"><Search className="absolute left-3 top-3.5 size-4 text-[var(--muted)]"/><input className="input pl-10" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search title or description"/></div><select className="select" value={categoryId} onChange={(e)=>{setCategoryId(e.target.value);setPage(1);}} aria-label="Category"><option value="">All categories</option>{categories.map((category)=><option key={category.id} value={category.id}>{category.name}</option>)}</select><select className="select" value={status} onChange={(e)=>{setStatus(e.target.value as ServiceStatus|"");setPage(1);}} aria-label="Status"><option value="">Any status</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></form>{loading?<LoadingState label="Finding services"/>:error?<ErrorMessage message={error}/>:services.length===0?<EmptyState title="No matching services" message="Try a broader search or remove a filter."/>:<div className="service-grid">{services.map((service)=><ServiceCard key={service.id} service={service}/>)}</div>}{!loading&&!error&&meta.totalPages>1&&<div className="pagination"><button className="icon-button" disabled={page<=1} onClick={()=>setPage(v=>v-1)} aria-label="Previous page"><ChevronLeft className="size-4"/></button><span>Page {meta.page} of {meta.totalPages}</span><button className="icon-button" disabled={page>=meta.totalPages} onClick={()=>setPage(v=>v+1)} aria-label="Next page"><ChevronRight className="size-4"/></button></div>}</div></main></>;
}
export default function ServicesPage(){return <Suspense fallback={<LoadingState label="Loading marketplace"/>}><ServicesContent/></Suspense>;}
